### ISSUE TITLE
Invalid oauth_verifier parameter with pin code

### ISSUE THREAD

**Issue by SebastianStehle** [CoreTweet/CoreTweet#163] opened 2018-08-29 16:02 UTC
Hi,

I have issues with authentication. The redirect to the pin code page works, but when I enter it I get the exception from the title:

    var session = await OAuth.AuthorizeAsync(twitterOptions.Value.ClientId, twitterOptions.Value.ClientSecret);
     
    return await session.GetTokensAsync(pinCode); // Invalid oauth_verifier parameter

**Comment by cannorin** [comment] 2018-08-29 16:32
Does the value of `pinCode` consists of numbers only (ex. “1234567”)? If it contains anything other than numbers (such as spaces or braces) it will produce that kind of error.

**Comment by SebastianStehle** [comment] 2018-08-29 16:40
Yes, only numbers.

**Comment by azyobuzin** [comment] 2018-08-29 16:47
I tested AuthorizeAsync and GetTokensAsync, but no exception was thrown.

**Comment by cannorin** [comment] 2018-08-29 16:49
Weird... Have you already got a dev account or are you using old consumer keys without it?

**Comment by azyobuzin** [comment] 2018-08-29 16:55
I remember that there was a bug occurring only with UWP previously. What are you running CoreTweet on? e.g. .NET Framework 4.7, .NET Core 2.1, Xamarin.Android, Xamarin.iOS, Windows 10 UWP, ...

**Comment by SebastianStehle** [comment] 2018-08-29 17:02
It is a brand new dev account. I am running it with .NET Core 2.1

**Comment by azyobuzin** [comment] 2018-08-29 17:26
I could not reproduce the exception on .NET Core 2.1 (SDK 2.1.401 on Windows 10).

```csharp
using System;
using System.Threading.Tasks;
using CoreTweet;

namespace ConsoleApp10
{
    class Program
    {
        static void Main(string[] args)
        {
            Run().Wait();
        }

        static async Task Run()
        {
            var session = await OAuth.AuthorizeAsync("key", "secret");
            Console.WriteLine(session.AuthorizeUri);
            Console.Write("PIN: ");
            var pin = Console.ReadLine();
            var tokens = await session.GetTokensAsync(pin);
            Console.WriteLine("OK");
        }
    }
}
```

I don't have a new developer account (I'm waiting for a reply from Twitter), so I cannot investigate it anymore.

**Comment by cannorin** [comment] 2018-08-29 17:28
I have no idea why it is not working... Could you show me a detailed source code you are working on?

**Comment by cannorin** [comment] 2018-08-29 17:36
I have a dev account so I’ll try reproducing it  later (I don’t have my laptop on hand right now).

**Comment by SebastianStehle** [comment] 2018-08-29 17:38
I think the problem was on my side and a misunderstanding about the flow. I have to use the same session object that was used to generate the authorize url to also generate the tokens with the pin code. This is not the case in my webapp.

**Comment by azyobuzin** [comment] 2018-08-29 17:42
You can re-create OAuthSession object like

```csharp
var session = new OAuth.OAuthSession {
    ConsumerKey = "",
    ConsumerSecret = "",
    RequestToken = "",
    RequestTokenSecret = "",
}
```

Then, call `session.GetTokensAsync`.

**Comment by cannorin** [comment] 2018-08-29 17:42
Oh that makes sense.. Have you read the [wiki](https://github.com/CoreTweet/CoreTweet/wiki/Authentication)? If you feel that confusing I’ll add some notes about it.

**Comment by SebastianStehle** [comment] 2018-08-29 17:48
@azyobuzin Then I get another exception: "Reverse auth credentials are invalid" 

@cannorin Yes I read it, but I have not  realized this problem. I am looking for a simple way to give my backend access to the twitter API.

**Comment by azyobuzin** [comment] 2018-08-29 17:59
@SebastianStehle That exception was reproduced using OAuthSession whose properties were set the empty string. I was updated the comment ( https://github.com/CoreTweet/CoreTweet/issues/163#issuecomment-417041818 ). Please check it.

**Comment by cannorin** [comment] 2018-08-29 18:02
The simplest working example would be the one above: 
https://github.com/CoreTweet/CoreTweet/issues/163#issuecomment-417036650
You can re-create an `OAuthSession` object like in this: 
https://github.com/CoreTweet/CoreTweet/issues/135#issuecomment-252233496

**Comment by SebastianStehle** [comment] 2018-08-29 18:09
Yes, I got it. But twitter integration is only a nice to have feature. I have 3 web servers and no need for sessions yet, so I either have to integrate a session store with redis or another shared storage or implement something similar. Probably too much effort just for twitter integration.

Damn.

**Comment by cannorin** [comment] 2018-08-29 18:16
Once you have got the `Tokens` with `session.GetTokensAsync`, you can [save and reuse it](
https://github.com/CoreTweet/CoreTweet/wiki/Saving-and-Reusing-Tokens-Howto) without authenticating it again.

**Comment by SebastianStehle** [comment] 2018-08-29 19:47
Thx. It works now :)

**Comment by cannorin** [comment] 2018-08-30 05:51
I’ll close this but if you encounter another problem please (don’t hesitate to) open a new one.

**Closed by cannorin** 2018-08-30 05:51 UTC
Labels: question
