### ISSUE TITLE
Does CoreTweet support three-legged OAuth (without a PIN)?

### ISSUE THREAD

**Issue by martingagne** [CoreTweet/CoreTweet#145] opened 2017-06-29 17:28 UTC
Does CoreTweet support three-legged OAuth (without a PIN)? I could not figure out how to do it...

https://dev.twitter.com/oauth/3-legged

I tried the following and could not get it to work. The token appears to be invalid.

```
        public async Task<ActionResult> TwitterAuth()
        {
            var twitterHelper = new TwitterHelper(this.settingManager);
            var consumerCreds = await twitterHelper.GetConsumerCredentials();
            var oAuthSession = await OAuth.AuthorizeAsync(consumerCreds.consumerKey, consumerCreds.consumerSecret, oauthCallback: "http://localhost:62114/Social/ValidateTwitterAuth");

            return new RedirectResult(oAuthSession.AuthorizeUri.AbsoluteUri);
        }

        public async Task<ActionResult> ValidateTwitterAuth(string oauth_token, string oauth_verifier)
        {
            var twitterHelper = new TwitterHelper(this.settingManager);
            var consumerCreds = await twitterHelper.GetConsumerCredentials();
            Tokens t = Tokens.Create(consumerCreds.consumerKey, consumerCreds.consumerSecret, oauth_token, oauth_verifier);

            // Fails on Friends.ListAsync. Invalid token.
            foreach (var item in await t.Friends.ListAsync())
            {
                Debug.WriteLine(item);
            }

            return Ok();
        }
```

**Comment by cannorin** [comment] 2017-06-30 00:24
Duplicate of https://github.com/CoreTweet/CoreTweet/issues/135 .

@azyobuzin btw I'm starting to think it is good to setup Gitter or something to receive questions. What do you think about?

**Closed by cannorin** 2017-06-30 00:24 UTC
Labels: duplicate, question

**Comment by azyobuzin** [comment] 2017-06-30 01:35
@cannorin I think it is good too!
